### ISSUE TITLE
fizzbuzz 구현

### ISSUE THREAD

**Issue by slksun** [slksun/fizzbuzz-for-me#1]
## 목표

나 혼자 완성해보는 fizzbuzz

## 요구사항

- 범위: 1~20까지의 정수

## Tasks

- [x] Print 'fizz' if i is times of 3.
- [x] Print 'buzz' if i is times of 5.
- [x] Print 'fizzbuzz' if i is time of 15.
- [x] Print i itself for any other cases.

## References

- https://en.wikipedia.org/wiki/Fizz_buzz
